INSERT INTO tbAeroporto (nomeAeroporto, siglaAeroporto, pais, cidade, regiao, endereco, fkEmpresa) VALUES
('Aeroporto Internacional de São Paulo', 'SBGR', 'Brasil', 'Guarulhos', 'SP','Rodovia Hélio Smidt, s/n', 2),
('Galeão', 'SBGL', 'Brasil', 'Rio de Janeiro', 'RJ','Av. Vinte de Janeiro, s/n', 2),
('Juscelino Kubitschek', 'SBBR', 'Brasil', 'Brasília','GO', 'SGAS Quadra 515, s/n', 2),
('Eduardo Gomes', 'SBEG', 'Brasil', 'Manaus','AM', 'Rodovia AM-070, km 11', 2),
('Deputado Luís Eduardo Magalhães', 'SBSV', 'Brasil', 'Salvador','BA', 'Av. Tancredo Neves, s/n', 2),
('Pinto Martins', 'SBFZ', 'Brasil', 'Fortaleza','BA', 'Av. Senador Carlos Jereissati, 3155', 2),
('Gilberto Freyre', 'SBRF', 'Brasil', 'Recife','PE', 'Av. Marechal Mascarenhas de Moraes, s/n', 2),
('Salgado Filho', 'SBPA', 'Brasil', 'Porto Alegre', 'RS', 'Av. Severo Dullius, s/n', 2),
('Afonso Pena', 'SBCT', 'Brasil', 'Curitiba','PR', 'Av. Afonso Pena, km 33, s/n', 2),
('Confins', 'SBCF', 'Brasil', 'Belo Horizonte','BH', 'Rodovia BR-356, km 464, s/n', 1),
('Congonhas', 'SBSP', 'Brasil', 'São Paulo', 'SP','Av. Washington Luís, s/n', 1),
('Hercílio Luz', 'SBFL', 'Brasil', 'Florianópolis', 'SC','Rodovia SC-401, km 49, s/n', 1),
('Augusto Severo', 'SBNT', 'Brasil', 'Natal', 'RN','Av. Capitão-aviador Alberto Santos Dumont', 1),
('Castro Pinto', 'SBJP', 'Brasil', 'João Pessoa','PB', 'Av. Marechal Eurico Gaspar Dutra, s/n', 1),
('Júlio Cezar Ribeiro', 'SBBE', 'Brasil', 'Belém', 'PA','Rodovia BR-316, km 8, s/n', 1),
('Marechal Rondon', 'SBCY', 'Brasil', 'Cuiabá','MT', 'Rodovia BR-163, km 294, s/n', 1),
('Zumbi dos Palmares', 'SBMO', 'Brasil', 'Maceió','AL', 'Av. Menino Marcelo, s/n', 1),
('Eurico de Aguiar Salles', 'SBVT', 'Brasil', 'Vitória', 'ES','Rodovia BR-101, km 39, s/n', 1);
